dist: trusty
language: node_js
sudo: 'false'
node_js: '9'
addons:
  firefox: latest
  chrome: stable
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
env:
  global:
    - secure: >-
        B0xDV89miqJ4dmIVXIrmyOZrAxBESJddq71dlxH9/xjAtW1y+1cwsOni19z5TvAhXyiiSxTkoVsZjnsbVfCBl2mfk5mKonfqsrlVebgJHmTsMJy+Hfh1WPi522EoxsX3BLnbWutUtCZog+qr+rBCAJ0no7xLxMpQPD9DCMRPis9zhjNoMYMMHj0kOPUpAmTqqh2rysinat7E5yVZ1slrEHcRHDklJES1QWRw31HSxVJ1fWqpRTasG2OcHMZRYTyJeEpDXjtmdKLmF/2H8boXhhmNOsPj1gO7PQHOJhQ3ZBrMV6EVihvB+Czf2ZmPIEviLLexAjkDvE3e76tOZz2TQZXSQqo/Xklxv2UoqnJVB5S2sZMF63BV5MCO+p4z4neTdvIqHxIUOMrEBW8x2UDeBMr5fPJiR63BMxjgytXBZFb9PxZ3wFb9yE+6b7Qos9FDK0zGLc2lIJr5BRsgTdkrC4nO+uX0VRmymwTL8dzhj+zKPz/mEQubunvHYnpszUq5RIdMQ+4oWCeaGc7w3sskspMIsu7stIyYGvKJWO5OVddyZSQwc+U/faoOc1Mz1vFwYCn2tEPvKKjGBLR4ZEW/+WuPKtooreyMIuVhm3QDFn11XvGVs8AfSpcOUZ+lwt3zx97OTwZeHA3ruQUmtyF+KZBU370mK48lvuHwd64NAbk=
    - secure: >-
        FCgPQHM8XonQKNf2GkiH6rHgougj6/LWhylsy51ZiTLOo1W19bRZyqte58U8MNOgBEscEUaS2SvOGeahF++tbaZWAU/5BfX242xif4F9KsBWsl6OUGFgimskkM28PifnWDfA5i/hpEmcPhJx+tm9g1kgHCXnhqw/Mcmp5I9vxxkr8hjOn9IiZldzTMqXqjgDgfATTHV0CsA79jEVvFwkxB1zOtePRt5h+GTp9neUNsRS7RkUUL/o6D8A5Tuq/4/5ijLglhR0MGWqzrWmbUxAdfJXhLJTMiMBXGNLdctiqos9N9ZIYMP0F/VmuXrp3x0io68jK/a2+q10N5ylHv/Sn61PiooC27tUOuOEQgVvmcc0l/MEqGltyCQozHK+upudM9cFLV8KAbtnvxwhHvaAIihYmaf7kZSjcMflK0MKnPT1JN4yUKecc1u6mIqXPdFAxoYk2p+tEy2yKXUs+bWbAkYC+5gJ7myDJ1mY4OoZe1M77VG4s28+Y+3p5gb0GbIB8mihkTyodUazfowoMCKioZVkozYukpeDfMeku6DcpK3DTwLA5RQtt4oktFtZceIIS3QjWD5h+sOqbXs5BBg0Y6CqHrtebJcTp3MJZy8VaNdbJbwwDmmRz2MHbFctEoLF7GNoNqDulr04qnCnnW3k+4bTCHXrfU3x6F2woWbTJLY=
cache:
  directories:
    - node_modules
